/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const WebLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const BackgroundConfig = IDL.Record({
  'blogCardImageUrl' : IDL.Opt(IDL.Text),
  'linksCardImageUrl' : IDL.Opt(IDL.Text),
  'aboutCardColor' : IDL.Opt(IDL.Text),
  'linksCardColor' : IDL.Opt(IDL.Text),
  'aboutCardImageUrl' : IDL.Opt(IDL.Text),
  'pageBackgroundImageUrl' : IDL.Opt(IDL.Text),
  'pageBackgroundColor' : IDL.Opt(IDL.Text),
  'blogCardColor' : IDL.Opt(IDL.Text),
});
export const CaffeineInfo = IDL.Record({
  'content' : IDL.Text,
  'lastUpdated' : Time,
});
export const CaffeineInfoScreenRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'mediaUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HeadingConfig = IDL.Record({
  'backgroundColor' : IDL.Opt(IDL.Text),
  'backgroundImageUrl' : IDL.Opt(IDL.Text),
  'font' : IDL.Text,
  'color' : IDL.Text,
  'text' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addWebLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteWebLink' : IDL.Func([IDL.Nat], [], []),
  'editBlogPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'editWebLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
  'getBackgroundConfig' : IDL.Func([], [BackgroundConfig], ['query']),
  'getCaffeineInfo' : IDL.Func([], [IDL.Opt(CaffeineInfo)], ['query']),
  'getCaffeineInfoConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'screens' : IDL.Vec(CaffeineInfoScreenRecord),
          'sectionTitle' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHeadingConfig' : IDL.Func([], [HeadingConfig], ['query']),
  'getOrderedWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitCount' : IDL.Func([], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderWebLinks' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBackgroundConfig' : IDL.Func([BackgroundConfig], [], []),
  'updateCaffeineInfo' : IDL.Func([IDL.Text], [], []),
  'updateCaffeineInfoConfig' : IDL.Func(
      [IDL.Text, IDL.Vec(CaffeineInfoScreenRecord)],
      [],
      [],
    ),
  'updateHeadingConfig' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const WebLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const BackgroundConfig = IDL.Record({
    'blogCardImageUrl' : IDL.Opt(IDL.Text),
    'linksCardImageUrl' : IDL.Opt(IDL.Text),
    'aboutCardColor' : IDL.Opt(IDL.Text),
    'linksCardColor' : IDL.Opt(IDL.Text),
    'aboutCardImageUrl' : IDL.Opt(IDL.Text),
    'pageBackgroundImageUrl' : IDL.Opt(IDL.Text),
    'pageBackgroundColor' : IDL.Opt(IDL.Text),
    'blogCardColor' : IDL.Opt(IDL.Text),
  });
  const CaffeineInfo = IDL.Record({
    'content' : IDL.Text,
    'lastUpdated' : Time,
  });
  const CaffeineInfoScreenRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'mediaUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HeadingConfig = IDL.Record({
    'backgroundColor' : IDL.Opt(IDL.Text),
    'backgroundImageUrl' : IDL.Opt(IDL.Text),
    'font' : IDL.Text,
    'color' : IDL.Text,
    'text' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addWebLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteWebLink' : IDL.Func([IDL.Nat], [], []),
    'editBlogPost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'editWebLink' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllAdminPrincipals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
    'getBackgroundConfig' : IDL.Func([], [BackgroundConfig], ['query']),
    'getCaffeineInfo' : IDL.Func([], [IDL.Opt(CaffeineInfo)], ['query']),
    'getCaffeineInfoConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'screens' : IDL.Vec(CaffeineInfoScreenRecord),
            'sectionTitle' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHeadingConfig' : IDL.Func([], [HeadingConfig], ['query']),
    'getOrderedWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitCount' : IDL.Func([], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderWebLinks' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBackgroundConfig' : IDL.Func([BackgroundConfig], [], []),
    'updateCaffeineInfo' : IDL.Func([IDL.Text], [], []),
    'updateCaffeineInfoConfig' : IDL.Func(
        [IDL.Text, IDL.Vec(CaffeineInfoScreenRecord)],
        [],
        [],
      ),
    'updateHeadingConfig' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };