/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackgroundConfig {
  'blogCardImageUrl' : [] | [string],
  'linksCardImageUrl' : [] | [string],
  'aboutCardColor' : [] | [string],
  'linksCardColor' : [] | [string],
  'aboutCardImageUrl' : [] | [string],
  'pageBackgroundImageUrl' : [] | [string],
  'pageBackgroundColor' : [] | [string],
  'blogCardColor' : [] | [string],
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface CaffeineInfo { 'content' : string, 'lastUpdated' : Time }
export interface CaffeineInfoScreenRecord {
  'id' : string,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'mediaUrl' : [] | [string],
}
export interface HeadingConfig {
  'backgroundColor' : [] | [string],
  'backgroundImageUrl' : [] | [string],
  'font' : string,
  'color' : string,
  'text' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebLink {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string], undefined>,
  'addWebLink' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteWebLink' : ActorMethod<[bigint], undefined>,
  'editBlogPost' : ActorMethod<[bigint, string, string], undefined>,
  'editWebLink' : ActorMethod<[bigint, string, string, string], undefined>,
  'getAllAdminPrincipals' : ActorMethod<[], Array<Principal>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllWebLinks' : ActorMethod<[], Array<WebLink>>,
  'getBackgroundConfig' : ActorMethod<[], BackgroundConfig>,
  'getCaffeineInfo' : ActorMethod<[], [] | [CaffeineInfo]>,
  'getCaffeineInfoConfig' : ActorMethod<
    [],
    { 'screens' : Array<CaffeineInfoScreenRecord>, 'sectionTitle' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHeadingConfig' : ActorMethod<[], HeadingConfig>,
  'getOrderedWebLinks' : ActorMethod<[], Array<WebLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitCount' : ActorMethod<[], bigint>,
  'incrementVisitCount' : ActorMethod<[], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderWebLinks' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBackgroundConfig' : ActorMethod<[BackgroundConfig], undefined>,
  'updateCaffeineInfo' : ActorMethod<[string], undefined>,
  'updateCaffeineInfoConfig' : ActorMethod<
    [string, Array<CaffeineInfoScreenRecord>],
    undefined
  >,
  'updateHeadingConfig' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];