/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    author: Principal;
    timestamp: Time;
}
export interface BackgroundConfig {
    blogCardImageUrl?: string;
    linksCardImageUrl?: string;
    aboutCardColor?: string;
    linksCardColor?: string;
    aboutCardImageUrl?: string;
    pageBackgroundImageUrl?: string;
    pageBackgroundColor?: string;
    blogCardColor?: string;
}
export type Time = bigint;
export interface HeadingConfig {
    backgroundColor?: string;
    backgroundImageUrl?: string;
    font: string;
    color: string;
    text: string;
}
export interface WebLink {
    id: bigint;
    url: string;
    title: string;
    description: string;
}
export interface CaffeineInfo {
    content: string;
    lastUpdated: Time;
}
export interface CaffeineInfoScreenRecord {
    id: string;
    title: string;
    content: string;
    order: bigint;
    mediaUrl?: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addBlogPost(title: string, content: string): Promise<void>;
    addWebLink(title: string, url: string, description: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBlogPost(id: bigint): Promise<void>;
    deleteWebLink(id: bigint): Promise<void>;
    editBlogPost(id: bigint, title: string, content: string): Promise<void>;
    editWebLink(id: bigint, title: string, url: string, description: string): Promise<void>;
    getAllAdminPrincipals(): Promise<Array<Principal>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllWebLinks(): Promise<Array<WebLink>>;
    getBackgroundConfig(): Promise<BackgroundConfig>;
    getCaffeineInfo(): Promise<CaffeineInfo | null>;
    getCaffeineInfoConfig(): Promise<{
        screens: Array<CaffeineInfoScreenRecord>;
        sectionTitle: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHeadingConfig(): Promise<HeadingConfig>;
    getOrderedWebLinks(): Promise<Array<WebLink>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisitCount(): Promise<bigint>;
    incrementVisitCount(): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    reorderWebLinks(newOrder: Array<bigint>): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBackgroundConfig(config: BackgroundConfig): Promise<void>;
    updateCaffeineInfo(content: string): Promise<void>;
    updateCaffeineInfoConfig(sectionTitle: string, screens: Array<CaffeineInfoScreenRecord>): Promise<void>;
    updateHeadingConfig(text: string, font: string, color: string, backgroundColor: string | null, backgroundImageUrl: string | null): Promise<void>;
}
import type { BackgroundConfig as _BackgroundConfig, CaffeineInfo as _CaffeineInfo, CaffeineInfoScreenRecord as _CaffeineInfoScreenRecord, HeadingConfig as _HeadingConfig, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1);
            return result;
        }
    }
    async addWebLink(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWebLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWebLink(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteWebLink(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWebLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWebLink(arg0);
            return result;
        }
    }
    async editBlogPost(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editBlogPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBlogPost(arg0, arg1, arg2);
            return result;
        }
    }
    async editWebLink(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editWebLink(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWebLink(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllAdminPrincipals(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdminPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdminPrincipals();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getAllWebLinks(): Promise<Array<WebLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWebLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWebLinks();
            return result;
        }
    }
    async getBackgroundConfig(): Promise<BackgroundConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundConfig();
                return from_candid_BackgroundConfig_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundConfig();
            return from_candid_BackgroundConfig_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaffeineInfo(): Promise<CaffeineInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaffeineInfo();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaffeineInfo();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaffeineInfoConfig(): Promise<{
        screens: Array<CaffeineInfoScreenRecord>;
        sectionTitle: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaffeineInfoConfig();
                return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaffeineInfoConfig();
            return from_candid_record_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeadingConfig(): Promise<HeadingConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeadingConfig();
                return from_candid_HeadingConfig_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeadingConfig();
            return from_candid_HeadingConfig_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderedWebLinks(): Promise<Array<WebLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderedWebLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderedWebLinks();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitCount();
            return result;
        }
    }
    async incrementVisitCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementVisitCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementVisitCount();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reorderWebLinks(arg0: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderWebLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderWebLinks(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBackgroundConfig(arg0: BackgroundConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBackgroundConfig(to_candid_BackgroundConfig_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBackgroundConfig(to_candid_BackgroundConfig_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCaffeineInfo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaffeineInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaffeineInfo(arg0);
            return result;
        }
    }
    async updateCaffeineInfoConfig(arg0: string, arg1: Array<CaffeineInfoScreenRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaffeineInfoConfig(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaffeineInfoConfig(arg0, to_candid_vec_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHeadingConfig(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeadingConfig(arg0, arg1, arg2, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeadingConfig(arg0, arg1, arg2, to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_BackgroundConfig_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BackgroundConfig): BackgroundConfig {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CaffeineInfoScreenRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineInfoScreenRecord): CaffeineInfoScreenRecord {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HeadingConfig_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeadingConfig): HeadingConfig {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaffeineInfo]): CaffeineInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    order: bigint;
    mediaUrl: [] | [string];
}): {
    id: string;
    title: string;
    content: string;
    order: bigint;
    mediaUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        order: value.order,
        mediaUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.mediaUrl))
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundColor: [] | [string];
    backgroundImageUrl: [] | [string];
    font: string;
    color: string;
    text: string;
}): {
    backgroundColor?: string;
    backgroundImageUrl?: string;
    font: string;
    color: string;
    text: string;
} {
    return {
        backgroundColor: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.backgroundColor)),
        backgroundImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.backgroundImageUrl)),
        font: value.font,
        color: value.color,
        text: value.text
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blogCardImageUrl: [] | [string];
    linksCardImageUrl: [] | [string];
    aboutCardColor: [] | [string];
    linksCardColor: [] | [string];
    aboutCardImageUrl: [] | [string];
    pageBackgroundImageUrl: [] | [string];
    pageBackgroundColor: [] | [string];
    blogCardColor: [] | [string];
}): {
    blogCardImageUrl?: string;
    linksCardImageUrl?: string;
    aboutCardColor?: string;
    linksCardColor?: string;
    aboutCardImageUrl?: string;
    pageBackgroundImageUrl?: string;
    pageBackgroundColor?: string;
    blogCardColor?: string;
} {
    return {
        blogCardImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.blogCardImageUrl)),
        linksCardImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.linksCardImageUrl)),
        aboutCardColor: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.aboutCardColor)),
        linksCardColor: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.linksCardColor)),
        aboutCardImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.aboutCardImageUrl)),
        pageBackgroundImageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pageBackgroundImageUrl)),
        pageBackgroundColor: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pageBackgroundColor)),
        blogCardColor: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.blogCardColor))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    screens: Array<_CaffeineInfoScreenRecord>;
    sectionTitle: string;
}): {
    screens: Array<CaffeineInfoScreenRecord>;
    sectionTitle: string;
} {
    return {
        screens: from_candid_vec_n8(_uploadFile, _downloadFile, value.screens),
        sectionTitle: value.sectionTitle
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaffeineInfoScreenRecord>): Array<CaffeineInfoScreenRecord> {
    return value.map((x)=>from_candid_CaffeineInfoScreenRecord_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BackgroundConfig_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BackgroundConfig): _BackgroundConfig {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_CaffeineInfoScreenRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaffeineInfoScreenRecord): _CaffeineInfoScreenRecord {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blogCardImageUrl?: string;
    linksCardImageUrl?: string;
    aboutCardColor?: string;
    linksCardColor?: string;
    aboutCardImageUrl?: string;
    pageBackgroundImageUrl?: string;
    pageBackgroundColor?: string;
    blogCardColor?: string;
}): {
    blogCardImageUrl: [] | [string];
    linksCardImageUrl: [] | [string];
    aboutCardColor: [] | [string];
    linksCardColor: [] | [string];
    aboutCardImageUrl: [] | [string];
    pageBackgroundImageUrl: [] | [string];
    pageBackgroundColor: [] | [string];
    blogCardColor: [] | [string];
} {
    return {
        blogCardImageUrl: value.blogCardImageUrl ? candid_some(value.blogCardImageUrl) : candid_none(),
        linksCardImageUrl: value.linksCardImageUrl ? candid_some(value.linksCardImageUrl) : candid_none(),
        aboutCardColor: value.aboutCardColor ? candid_some(value.aboutCardColor) : candid_none(),
        linksCardColor: value.linksCardColor ? candid_some(value.linksCardColor) : candid_none(),
        aboutCardImageUrl: value.aboutCardImageUrl ? candid_some(value.aboutCardImageUrl) : candid_none(),
        pageBackgroundImageUrl: value.pageBackgroundImageUrl ? candid_some(value.pageBackgroundImageUrl) : candid_none(),
        pageBackgroundColor: value.pageBackgroundColor ? candid_some(value.pageBackgroundColor) : candid_none(),
        blogCardColor: value.blogCardColor ? candid_some(value.blogCardColor) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    order: bigint;
    mediaUrl?: string;
}): {
    id: string;
    title: string;
    content: string;
    order: bigint;
    mediaUrl: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        order: value.order,
        mediaUrl: value.mediaUrl ? candid_some(value.mediaUrl) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CaffeineInfoScreenRecord>): Array<_CaffeineInfoScreenRecord> {
    return value.map((x)=>to_candid_CaffeineInfoScreenRecord_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
